-- Index supporting the api_idempotency_keys TTL cleanup query.
--
-- The cleanup job (handle_cleanup_idempotency_keys) runs hourly and
-- deletes rows older than 24 hours. Without an index leading on
-- created_at, that DELETE is a sequential scan over the (org_id, key)
-- B-tree — fast at hundreds of rows, painful at millions.
--
-- Note on partial-index attempt: the initial version of this index
-- used `WHERE created_at < (now() - INTERVAL '24 hours')` to keep the
-- index tiny. Postgres rejects that with
--   ERROR: functions in index predicate must be marked IMMUTABLE
-- because `now()` is STABLE, not IMMUTABLE — the index contents
-- couldn't be guaranteed consistent over time. The plain (created_at)
-- index covers the cleanup DELETE's range scan equally well; the
-- only loss vs. the partial form is index size (proportional to row
-- count vs. proportional to a 1-hour insert burst). At pilot scale
-- the difference is negligible; the cleanup job's hourly cadence
-- keeps the table itself bounded so the index stays small too.
--
-- IF NOT EXISTS so this migration is replayable on environments that
-- somehow created it manually.
CREATE INDEX IF NOT EXISTS idx_api_idempotency_keys_cleanup
  ON api_idempotency_keys (created_at);
