/**
 * Phase 10 — D5 Pre-Approval Coaching.
 *
 * Pure, deterministic prompt generator. The MVP build spec describes
 * coaching as "generated by the LLM at review time," but five of the
 * canonical triggers (cumulative spend, terms mismatch, new line item,
 * unusual total, early-payment discount) are 100% computable from data
 * we already have. Going deterministic for MVP buys:
 *
 *   - No third LLM call → no token-quota / cost growth per invoice
 *   - No new Anthropic prompt boundary to police (PR11 hardening still
 *     holds without revisiting)
 *   - Reproducible — auditors can verify the prompts at any later date
 *   - Loss framing (F03) is a template choice; LLM polish isn't required
 *     to apply it consistently
 *
 * F03 — Behavioural nudges, loss-framed messaging. Each message
 * describes the financial / operational impact of APPROVING; messages
 * never frame the same fact as a gain ("you save X"). The bookkeeper
 * sees the consequence, not the upside.
 *
 * PII boundary (same rule as briefing card prose):
 *   - never name the vendor (use "this vendor")
 *   - never quote invoice number, PO number, address, EIN
 *   - dollar amounts in messages are OK only when they describe the
 *     financial impact of the action being prompted on (the
 *     approver's own decision space) — NOT the historical baseline
 *
 * The prompts are persisted on briefing_cards.coachingPromptsJson and
 * frozen at approve time via the pinned activeBriefingCardId (PR6).
 */

import type { ValidationFinding } from "@/lib/validation";

export type CoachingSeverity = "info" | "warning" | "critical";

export type CoachingCode =
  | "cumulative_spend_alert"
  | "terms_mismatch"
  | "new_line_item_coaching"
  | "unusual_total"
  | "early_payment_discount";

export interface CoachingPrompt {
  code: CoachingCode;
  severity: CoachingSeverity;
  /** Approver-facing, loss-framed, PII-clean. */
  message: string;
  /**
   * When the prompt describes a dollar impact, store the figure here so
   * the UI can render it consistently and the audit packet can join on
   * structured numbers. Null when the prompt is purely operational
   * (e.g. terms_mismatch with no $-impact estimate).
   */
  dollarImpact: number | null;
  /** Lightweight structured context for the evidence packet. */
  context: Record<string, string | number | boolean | null>;
}

export interface CoachingInputs {
  invoice: {
    total: number | null;
    currency: string | null;
    paymentTerms: string | null;
    /** Earliest discount-capture date for early-pay coaching. ISO. */
    invoiceDate: string | null;
    dueDate: string | null;
    /** PRD §"Line items" — when extraction has it, leave blank otherwise. */
    discountPct: number | null;
    discountAmount: number | null;
  };
  /**
   * Vendor longitudinal profile. Null when no vendor matched — coaching
   * still emits for the operational (terms / line item) triggers when
   * possible; spend-based triggers require it.
   */
  vendorProfile: {
    invoiceCount: number;
    spend30d: string; // Drizzle numeric → string
    avgInvoiceAmount: string;
    defaultPaymentTerms: string | null;
  } | null;
  /**
   * Active validation findings — used to fold the validator's
   * new_line_item warning into a coaching prompt (single source of
   * truth: if the validator said it's new, the coaching prompt agrees).
   */
  findings: ValidationFinding[];
}

// ── Trigger constants ──────────────────────────────────────────────────

/**
 * The cumulative spend trigger fires when approving this invoice would
 * push 30-day spend above this multiple of the vendor's average. 1.5×
 * roughly matches the "running 50% over typical run-rate" intuition
 * without firing on natural month-end clustering.
 */
const SPEND_RUN_RATE_MULTIPLIER = 1.5;
/**
 * Minimum vendor history before unusual_total fires. Below this we lack
 * a stable mean to compare against; the validator's `vendor_warming_up`
 * is the right signal until then.
 */
const UNUSUAL_TOTAL_MIN_INVOICES = 3;
/**
 * unusual_total fires when invoice total > avgInvoiceAmount × this.
 * 1.5 (50% above mean) is a defensible "double-check this one" line
 * without firing on routine spread.
 */
const UNUSUAL_TOTAL_MULTIPLIER = 1.5;

// ── Pure compute ──────────────────────────────────────────────────────

export function computeCoachingPrompts(
  inputs: CoachingInputs,
): CoachingPrompt[] {
  const prompts: CoachingPrompt[] = [];
  const { invoice, vendorProfile, findings } = inputs;

  // 1. Cumulative spend alert — fires when this single invoice would
  // materially lift the vendor's 30-day spend above their recent rate.
  //
  // Baseline: prefer `spend30` (an actual rolling 30-day rate
  // maintained by the recompute job). When spend30 is zero (truly
  // dormant vendor for 30 days), fall back to `avg` so we still
  // catch a sudden re-engagement at a high amount.
  if (
    invoice.total !== null &&
    vendorProfile &&
    vendorProfile.invoiceCount >= UNUSUAL_TOTAL_MIN_INVOICES
  ) {
    const spend30 = parseNumeric(vendorProfile.spend30d);
    const avg = parseNumeric(vendorProfile.avgInvoiceAmount);
    if (spend30 !== null && avg !== null && avg > 0) {
      const baseline = spend30 > 0 ? spend30 : avg;
      const projected = spend30 + invoice.total;
      if (projected > baseline * SPEND_RUN_RATE_MULTIPLIER) {
        const overage = projected - baseline;
        const pct = Math.round((overage / baseline) * 100);
        prompts.push({
          code: "cumulative_spend_alert",
          severity: "warning",
          message: `Approving lifts 30-day spend with this vendor about ${pct}% above the recent run-rate.`,
          dollarImpact: round2(overage),
          context: {
            projected30dSpend: round2(projected),
            priorSpend30: round2(spend30),
            avgInvoiceAmount: round2(avg),
            vendorInvoiceCount: vendorProfile.invoiceCount,
          },
        });
      }
    }
  }

  // 2. Terms mismatch — operational impact, no $ figure.
  if (
    vendorProfile?.defaultPaymentTerms &&
    invoice.paymentTerms &&
    !termsEqual(invoice.paymentTerms, vendorProfile.defaultPaymentTerms)
  ) {
    const invoiceDays = parseNetDays(invoice.paymentTerms);
    const onFileDays = parseNetDays(vendorProfile.defaultPaymentTerms);
    let message = `Approving uses payment terms that differ from this vendor's terms on file.`;
    if (invoiceDays !== null && onFileDays !== null) {
      const delta = onFileDays - invoiceDays;
      if (delta > 0) {
        message = `Approving on the invoice's terms accelerates payment by ~${delta} days vs. the terms on file for this vendor.`;
      } else if (delta < 0) {
        message = `Approving on the invoice's terms slows payment by ~${Math.abs(delta)} days vs. the terms on file for this vendor.`;
      }
    }
    prompts.push({
      code: "terms_mismatch",
      severity: "warning",
      message,
      dollarImpact: null,
      context: {
        invoiceTerms: invoice.paymentTerms,
        onFileTerms: vendorProfile.defaultPaymentTerms,
        invoiceDueDays: invoiceDays,
        onFileDueDays: onFileDays,
      },
    });
  }

  // 3. new_line_item — repackage validator's finding as coaching.
  // Single source of truth: the validator already decided whether
  // any keyword is new; we just reformulate as approver-facing prose.
  const newLineFinding = findings.find((f) => f.code === "new_line_item");
  if (newLineFinding) {
    const ctx = newLineFinding.context as
      | { lineNumbers?: number[] }
      | undefined;
    const count = Array.isArray(ctx?.lineNumbers) ? ctx!.lineNumbers!.length : 1;
    prompts.push({
      code: "new_line_item_coaching",
      severity: "warning",
      message:
        count === 1
          ? `Approving introduces 1 line item with no prior history from this vendor.`
          : `Approving introduces ${count} line items with no prior history from this vendor.`,
      dollarImpact: null,
      context: {
        newLineCount: count,
        // Line numbers reference the invoice we're reviewing — not
        // identifying on their own. Useful for the evidence packet.
        lineNumbers: JSON.stringify(ctx?.lineNumbers ?? []),
      },
    });
  }

  // 4. unusual_total — invoice total materially above vendor's typical.
  if (
    invoice.total !== null &&
    vendorProfile &&
    vendorProfile.invoiceCount >= UNUSUAL_TOTAL_MIN_INVOICES
  ) {
    const avg = parseNumeric(vendorProfile.avgInvoiceAmount);
    if (avg !== null && avg > 0 && invoice.total > avg * UNUSUAL_TOTAL_MULTIPLIER) {
      const pct = Math.round(((invoice.total - avg) / avg) * 100);
      prompts.push({
        code: "unusual_total",
        severity: "info",
        message: `Total is about ${pct}% above this vendor's typical invoice average.`,
        dollarImpact: round2(invoice.total - avg),
        context: {
          invoiceTotal: invoice.total,
          avgInvoiceAmount: round2(avg),
          variancePct: pct,
        },
      });
    }
  }

  // 5. Early payment discount opportunity — only when the invoice
  // carries discount fields. Loss framing: "skipping the discount
  // costs $X."
  if (
    invoice.total !== null &&
    invoice.discountPct !== null &&
    invoice.discountPct > 0
  ) {
    const discountValue = (invoice.total * invoice.discountPct) / 100;
    if (discountValue > 0.5) {
      prompts.push({
        code: "early_payment_discount",
        severity: "info",
        message: `Approving past the discount window forgoes a ${invoice.discountPct}% early-payment discount.`,
        dollarImpact: -round2(discountValue), // negative — money LEFT on the table
        context: {
          discountPct: invoice.discountPct,
          discountValue: round2(discountValue),
          invoiceDate: invoice.invoiceDate,
          dueDate: invoice.dueDate,
        },
      });
    }
  }

  return prompts;
}

// ── helpers ────────────────────────────────────────────────────────────

function parseNumeric(s: string | null): number | null {
  if (s === null || s === undefined) return null;
  const n = Number(s);
  return Number.isFinite(n) ? n : null;
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}

/**
 * Normalize a payment-terms string for equality comparison. "Net 30"
 * and "net 30" and " Net  30 " all collapse to "net 30". Returns the
 * raw normalized form; the caller decides whether identity matters.
 */
function normalizeTerms(s: string): string {
  return s.trim().toLowerCase().replace(/\s+/g, " ");
}

function termsEqual(a: string, b: string): boolean {
  return normalizeTerms(a) === normalizeTerms(b);
}

/**
 * Extract the "Net N" day count from a terms string. Returns null when
 * the string isn't of the form "Net N" (e.g. "Due on receipt", custom
 * arrangements). Used to compute the days-different signal for the
 * terms mismatch prompt.
 */
function parseNetDays(s: string): number | null {
  const m = normalizeTerms(s).match(/(?:^|\b)net\s+(\d{1,3})\b/);
  if (!m) return null;
  const n = Number(m[1]);
  return Number.isFinite(n) ? n : null;
}
